### ISSUE TITLE
Staging site deployed with circle CI

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#1]
As a developer I would like every commit to trigger an integration test and deployment

Definition of done:
a commit causes Circle CI to trigger

**Comment by NoopDog** [comment]
@afgane @kozbo is there a circle-ci account setup that we can use for anvil? If not, who can set this up for us and get me access?

Cheers and Thanks,
D

**Comment by kozbo** [comment]
I cannot set it up.

**Comment by afgane** [comment]
I setup a project on CircleCI for the `anvil-portal` repo and placed a copy of the default config file in #39, which will need to be updated to reflect the desired process. I don't see an option to add users in CircleCI interface so let me know if something else is needed.

**Comment by NoopDog** [comment]
Hi Kosbo yes I set it up so that a commit to the staging repo deploys to the staging site and that a commit to master deploys to master. 

https://circleci.com/gh/anvilproject

<img width="1037" alt="Screen Shot 2019-07-26 at 5 24 49 PM" src="https://user-images.githubusercontent.com/3239697/61987295-4bb63e00-afca-11e9-9c87-7a37f6f89f06.png">
