### ISSUE TITLE
Check portal pages on various browsers

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#29]
Latest  Firefox, Safari, MS Edge, Mobile Safari, Mobile Chrome

**Comment by frano-m** [comment]
- [x] mobile safari
- [x] mobile chrome
- [x] Firefox
- [x] Safari
- [x] MS Edge

@dave see attached image below for IE 11 (checked it while I was looking into MS Edge)...
It's hard to tell if the problem is genuine or BrowserStack related?

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/8e73c3fa-242f-4a09-a2cb-bc3ee94229c9)

**Comment by NoopDog** [comment]
@frano-m  I think it is likely an IE 11 problem. I do not think we need to support ie 11 so if it looks ok on all the other browsers, We can close this and see if anyone reports any problems with the their specific device/browser.

Thanks for checking!

Cheers,
D
