### ISSUE TITLE
Create staging deployment environment

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#35]

**Comment by NoopDog** [comment]
HI @afgane is this something you can setup? We need to get a staging site going and I am hoping you are the correct person to assign this ticket to. If not can you let me know who can do this for us? Thanks! D

**Comment by afgane** [comment]
This should be something I can setup and will try and do it later on today.
(The Galaxy conference ended yesterday so couldn't get to it before.)

**Comment by afgane** [comment]
A staging project is setup now. The site is available at https://staging.anvilproject.org/ and the deployment as `staging-anvil-portal` project on Firebase Hosting. @NoopDog you should have the necessary access. 

To deploy into that project, create a new local directory and run `firebase init` within it, selecting the `staging-anvil-portal` project as the deployment target.

At first I tried setting this up as a separate site within the original project but after several failed attempts, I came across the documentation where is says the recommended best practice is to keep _staging_ and _production_ as separate projects (https://firebase.google.com/docs/hosting/multisites), so that's where we are.
